version: '3.11'
services:
  postgres-db:
    container_name: postgres-db
    image: postgres:latest
    env_file:
      - .env
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data

  cassandra-db:
    container_name: cassandra-db
    image: cassandra:latest
    environment:
      - .env
    ports:
      - "9042:9042"
    volumes:
      - cassandra-data:/var/lib/cassandra
    restart:
      on-failure

  transaction-limit-service:
    container_name: transaction-limit-service
    image: transaction-limit-service:latest
    env_file:
      - .env
    ports:
      - "8082:8082"
    depends_on:
      - postgres-db
      - cassandra-db

volumes:
  cassandra-data:
  postgres-data: