version: '3.11'
services:
  postgres-db:
    container_name: postgres-db
    image: postgres:latest
    env_file:
      - .env
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart:
      on-failure
    healthcheck:
      test: pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}
      interval: 10s
      timeout: 3s
      retries: 3

  cassandra-db:
    container_name: cassandra-db
    image: cassandra:latest
    env_file:
      - .env
    ports:
      - "9042:9042"
    volumes:
      - cassandra-data:/var/lib/cassandra
    restart:
      on-failure
    healthcheck:
      test: cqlsh -u ${CASSANDRA_USER} -p ${CASSANDRA_PASSWORD}
      interval: 5s
      timeout: 10s
      retries: 30

  transaction-limit-service:
    container_name: transaction-limit-service
    image: transaction-limit-service:latest
    env_file:
      - .env
    ports:
      - "8082:8082"
    depends_on:
      postgres-db:
        condition: service_healthy
      cassandra-db:
        condition: service_healthy

volumes:
  cassandra-data:
  postgres-data: