server:
  forward-headers-strategy: native
  port: ${TRANSACTION_SERVICE_PORT}
spring:
  application:
    name: transaction-limit-service
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  flyway:
    schemas: public
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
  cassandra:
    contact-points: ${CASSANDRA_HOST}
    password: ${CASSANDRA_PASSWORD}
    keyspace-name: ${CASSANDRA_KEYSPACE_NAME}
    port: ${CASSANDRA_PORT}
    schema-action: create_if_not_exists
    local-datacenter: "datacenter1"
  open-exchanges:
    host: ${EXCHANGE_HOST}
    api: ${EXCHANGE_API}
    api-id: ${EXCHANGE_APP_ID}