server:
  port: ${TRANSACTION_SERVICE_PORT}
spring:
  application:
    name: transaction-limit-service
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  flyway:
    default-schema: public
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  cassandra:
    contact-points: ${CASSANDRA_HOST}:${CASSANDRA_PORT}
    password: ${CASSANDRA_PASSWORD}
